# Site settings
title: Writing Seminar Portoflio
email: exm8050@g.rit.edu
description: > # this means to ignore newlines until "baseurl:" 
baseurl: /College-Blog-v2.0 # the subpath of your site, e.g. /blog/
nodeurl: /about
url: "https://pyramidian.github.io/College-Blog-v2.0/" # the base hostname & protocol for your site
github_username:  Pyramidian

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Puppies
    link: https://www.google.com/search?q=puppies&num=20&espv=2&rlz=1C1CHBF_enUS707US707&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi3m4qmwefQAhWqhVQKHe6UDV8Q_AUICCgB&biw=1418&bih=669
  option2:
    name: More Puppies
    link: http://imgur.com/r/puppies
  option3:
    name: Even More Puppies
    link: https://www.tumblr.com/tagged/puppies

# Build settings
markdown: kramdown
highlighter: rouge

