# Site settings
title: College Blog
email: exm8050@g.rit.edu
description: > # this means to ignore newlines until "baseurl:" 
baseurl: /College-Blog-v2.0 # the subpath of your site, e.g. /blog/
nodeurl: /about
url: "https://pyramidian.github.io/College-Blog-v2.0/" # the base hostname & protocol for your site
github_username:  Pyramidian

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Miku.PWM
    link: http://brushlessmiku.xyz/
  option2:
    name: Ishraq's Blog
    link: www.leekspin.com
  option3:
    name: Equals Zero
    link: http://www.etotheipiplusone.net/

# Build settings
markdown: kramdown
highlighter: rouge

