# Site settings
title: Placeholder.title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A home for all projects, collaborations, and musings I have to take part in during my time at RIT.
baseurl: "/College-Blog-v2.0/" # the subpath of your site, e.g. /blog/
url: "https://pyramidian.github.io/College-Blog-v2.0/" # the base hostname & protocol for your site
twitter_username: Pyramidian
github_username:  Pyramidian

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

# Build settings
markdown: kramdown
